spring:
  application:
    name: auth-server
server:
  port: 8150
security:
  oauth2:
    resource:
      filter-order: 3
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:8110/eureka