server:
  port: 8120
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eurekasecond   #提供服务的域名，这里在hosts文件中修改了
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: #向eurekazero注册中心注册自己
        http://eurekazero:8100/eureka/,http://eurekafirst:8110/eureka/


